/**
 * Step `write --article <id>` — runs the TextOS writer on a prepared intake and packages the
 * result for the site.
 *
 * WHO WRITES THE SLOTS. TextOS's writer calls a slot provider once per slot. Its live provider
 * (`ClaudeGeoWriterSlotProvider`) sends TextOS's own prompt to the Anthropic API and parses the
 * reply with TextOS's strict slot parser; its transport is injectable by design. This run has no
 * API key, so the transport is the operator: the Claude Code session acting as ShortsOS CTO/CMO
 * answered each prompt exported by `prepare` (`responses/<slot>.json`). TextOS's own provider class
 * still builds the prompt and parses the answer, and before any answer is used the prompt TextOS
 * renders NOW must hash-match the prompt the answer was written against. The provider identity
 * recorded in the result says exactly that: `operator:claude-code|geo-writer-slot@<prompt version>`
 * — never the API model TextOS pins, which did not run.
 *
 * WHAT DECIDES. Nothing here judges the text: TextOS's writer enforces slot bounds, evidence
 * boundaries and declared statements; TextOS's TruthCheck decides pass / alert / block. A refused
 * outcome is written to disk and the step fails. Only a `pass` is packaged for the site.
 */
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

import { TEXTOS_DIR, TEXTOS_REF, argValue, loadTextos, readJson, sha256, writeJson, writeText } from "./lib";
import type { GeoWriterOutcome, SlotWriteRequest } from "./lib";
import type { CtcGeoWriterIntake, GeoWriterSlot } from "./textos-contracts";
import { FLOW_SURFACE, responseFileName, type ArticleBrief } from "../../../src/lib/textos/brief";

const CONTENT_TYPE = "ARTICLE";

function renderHumanReview(params: {
  brief: ArticleBrief;
  intake: CtcGeoWriterIntake;
  outcome: Extract<GeoWriterOutcome, { status: "written" }>;
  prohibitedByEntity: { id: string; prohibitedClaims: string[] }[];
}): string {
  const { brief, intake, outcome, prohibitedByEntity } = params;
  const evidenceById = new Map(intake.evidence.map((e) => [e.id, e]));
  const ledgerById = new Map(outcome.result.document.statementLedger.map((s) => [s.id, s]));
  const lines: string[] = [
    `# Human review — ${brief.articleId}`,
    "",
    "Generated by `npm run textos -- write`. Nothing below is a review: it is the packet a human reviews.",
    "Publication on the site was mandated by the ShortsOS owner; this per-article review is still PENDING.",
    "",
    `- Flow: \`${brief.flow}\` → manifest surface \`${FLOW_SURFACE[brief.flow]}\``,
    `- Channel the evidence was checked for: \`${brief.publicationChannel}\``,
    `- Buyer question: ${brief.provenance.buyerQuestion}`,
    `- Target query: ${brief.provenance.targetQuery} (${brief.provenance.targetQueryProvenance}; demand ${brief.provenance.demandEvidenceStatus})`,
    `- TruthCheck: **${outcome.result.truthCheck.verdict}** (${outcome.result.truthCheck.contradictions.length} finding(s))`,
    `- Writer: \`${outcome.result.derivationIdentity}\` — TextOS \`${TEXTOS_REF}\``,
    "",
    "## Slots, statements and the evidence each one cites",
    "",
  ];
  for (const slot of outcome.result.slots) {
    lines.push(`### ${slot.slotId} (${slot.role})${slot.heading ? ` — ${slot.heading}` : ""}`, "", `> ${slot.text}`, "");
    for (const id of slot.statementIds) {
      const st = ledgerById.get(id);
      if (!st) continue;
      lines.push(`- **${st.kind}** — ${st.text}`);
      for (const eid of st.evidenceIds) {
        const ev = evidenceById.get(eid);
        lines.push(`  - \`${eid}\` (${ev?.sourceTitle ?? "?"}): «${ev?.excerpt ?? "?"}»`);
      }
    }
    lines.push("");
  }
  lines.push(
    "## Prohibited claims to check by hand",
    "",
    "TextOS does not scan for these (a substring scan would block honest denials and miss paraphrases); the reviewer does.",
    "",
  );
  for (const entity of prohibitedByEntity) {
    lines.push(`**${entity.id}**`, "", ...entity.prohibitedClaims.map((c) => `- ${c}`), "");
  }
  lines.push(
    "## Reviewer checklist",
    "",
    "- [ ] Every factual sentence says no more than the evidence quoted under it.",
    "- [ ] No sentence implies self-serve access, general availability, repeated volume, or guaranteed quality or performance.",
    "- [ ] Historical statements are dated or clearly past; nothing reads as a current offer unless the manifest authorizes it on this surface.",
    "- [ ] Reviewer name and date recorded in the brief's review record.",
    "",
  );
  return lines.join("\n");
}

async function main(): Promise<void> {
  const articleId = argValue("--article");
  if (!articleId) throw new Error("write: --article <id> is required.");
  const runDir = join(TEXTOS_DIR, "runs", articleId);
  const brief = readJson<ArticleBrief>(join(TEXTOS_DIR, "briefs", `${articleId}.json`));
  const intake = readJson<CtcGeoWriterIntake>(join(runDir, "intake.json"));
  const prepared = readJson<{ executionPlanHash: string; promptHashes: Record<string, string> }>(join(runDir, "adapt.json"));

  const textos = await loadTextos();
  const adapted = textos.adaptCtcIntakeToExecutionPlan(intake);
  if (adapted.executionPlanHash !== prepared.executionPlanHash) {
    throw new Error("write: the intake no longer produces the plan `prepare` exported prompts for — re-run prepare.");
  }

  const promptVersion = textos.CLAUDE_GEO_WRITER_SLOT_METHOD_VERSION.split("|")[1];
  const operatorMethodVersion = `operator:claude-code|${promptVersion}`;
  const responseHashes: Record<string, string> = {};

  const slotsByPrompt = new Map<string, GeoWriterSlot>();
  for (const slot of adapted.plan.slots) {
    const expected = prepared.promptHashes[slot.id];
    if (!expected) throw new Error(`write: no exported prompt for slot ${slot.id}.`);
    slotsByPrompt.set(expected, slot);
  }

  // The operator transport: answers only a prompt identical to the one exported by `prepare`.
  const transport = async (system: string, user: string): Promise<unknown> => {
    const hash = sha256(`${system}\n\n${user}`);
    const slot = slotsByPrompt.get(hash);
    if (!slot) throw new Error("write: TextOS rendered a prompt that matches no exported prompt — re-run prepare.");
    const file = join(runDir, "responses", responseFileName(slot.id));
    if (!existsSync(file)) throw new Error(`write: no operator response for slot ${slot.id} (${file}).`);
    const raw = readFileSync(file, "utf8");
    responseHashes[slot.id] = sha256(raw);
    return { content: [{ type: "text", text: raw }] };
  };
  const textosProvider = new textos.ClaudeGeoWriterSlotProvider(transport);
  const provider = {
    methodVersion: operatorMethodVersion,
    writeSlot: (request: SlotWriteRequest) => textosProvider.writeSlot(request),
  };

  const outcome = await textos.writeGroundedSlots(adapted.plan, provider);
  writeJson(join(runDir, "writer-outcome.json"), outcome);
  if (outcome.status !== "written") {
    throw new Error(`write: TextOS refused ${articleId} — ${outcome.reason} (slot ${outcome.slotId ?? "<document>"}): ${outcome.detail}`);
  }
  if (outcome.result.truthCheck.verdict !== "pass") {
    throw new Error(
      `write: TruthCheck verdict is ${outcome.result.truthCheck.verdict}, not pass — ` +
        outcome.result.truthCheck.contradictions.map((c) => `[${c.severity}] ${c.reason} «${c.unit}»`).join("; "),
    );
  }

  const bridge = textos.bridgeGeoWriterResultToContentDocument({
    outcome,
    documentId: `shortsos:${articleId}`,
    slug: brief.slug,
    language: brief.locale,
    contentType: CONTENT_TYPE,
    provenance: adapted.provenance,
    allowedSurfaces: ["reference"],
  });

  const policies = readJson<{ policies: Record<string, unknown> }>(join(TEXTOS_DIR, "client", "surface-policy.json")).policies;
  const policy = textos.SurfacePolicySchema.parse(policies[FLOW_SURFACE[brief.flow]]);
  const resolved = textos.resolveContentSurface(bridge.document, policy, []);
  const withReadingTime = textos.withReadingTime(resolved, bridge.document);
  const structure = textos.computeContentTypePolicy(CONTENT_TYPE, bridge.document);
  const resolvedJson = `${textos.serializeResolvedContentSurfaceToJson(withReadingTime)}\n`;

  const { document, ...lineage } = bridge;
  writeJson(join(runDir, "content-document.json"), document);
  writeText(join(runDir, "resolved-surface.json"), resolvedJson);
  writeJson(join(runDir, "article-structure.json"), structure);
  writeJson(join(runDir, "lineage.json"), lineage);

  const manifest = readJson<{ entities: { id: string; prohibitedClaims: string[] }[] }>(
    join(TEXTOS_DIR, "..", "content-bundles", "inputs", "manifest.json"),
  );
  const prohibitedByEntity = brief.entityIds
    .map((id) => manifest.entities.find((e) => e.id === id))
    .filter((e): e is { id: string; prohibitedClaims: string[] } => Boolean(e && e.prohibitedClaims.length > 0));
  writeText(join(runDir, "HUMAN-REVIEW.md"), renderHumanReview({ brief, intake, outcome, prohibitedByEntity }));

  writeJson(join(runDir, "receipt.json"), {
    receiptVersion: 1,
    articleId,
    textos: { repository: "gangster-nerd/textos-v0", sha: TEXTOS_REF },
    adapterMethodVersion: adapted.adapterMethodVersion,
    executionPlanHash: adapted.executionPlanHash,
    ctcHandoffHash: adapted.ctcHandoffHash,
    writerMethodVersion: outcome.result.writerMethodVersion,
    slotProviderMethodVersion: outcome.result.slotProviderMethodVersion,
    derivationIdentity: outcome.result.derivationIdentity,
    structuredContentHash: outcome.result.structuredContentHash,
    truthCheckVerdict: outcome.result.truthCheck.verdict,
    publicationChannel: brief.publicationChannel,
    canonicalProductSha: bridge.canonicalProductSha,
    promptHashes: prepared.promptHashes,
    responseHashes,
    contentDocumentSha256: sha256(`${JSON.stringify(document, null, 2)}\n`),
    resolvedSurfaceSha256: sha256(resolvedJson),
    humanReview: "pending",
  });

  console.log(`write: ${articleId} written.`);
  console.log(`  TruthCheck:  ${outcome.result.truthCheck.verdict}`);
  console.log(`  derivation:  ${outcome.result.derivationIdentity}`);
  console.log(`  reading:     ${withReadingTime.readingTimeMinutes} min`);
  console.log(`  slots:       ${outcome.result.slots.length}`);
}

await main();
